# version: '3'
# services:

#         db:
#             container_name: postgres_db
#             image: 'postgres'
#             environment:
#                 POSTGRES_PASSWORD: '1234'
#                 POSTGRES_USER: danah
#                 POSTGRES_DB: myDB
#             ports:
#               - "5432:5432"
#             volumes:
#               - ./init.sql:/docker-entrypoint-initdb.d/init.sql

        # app:
        #     image: my_node_app
        #     ports:
        #         - '8080:8080'

version: '3.8'

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      # - POSTGRES_DB= myDB

    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      # - db:/var/lib/postgresql/data
      
  app:
    image: my_node_app
    ports:
      - '8080:8080'
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      DB_PORT: 5432
      # POSTGRES_DB: "myDB"

volumes:
  db:
    driver: local

